steps:
- id: 'ls'
  name: "sh"
  args:
    - "-c"
    - |
      echo "hello"
      pwd
      ls -la
- id: 'yarn'
  name: 'gcr.io/cloud-builders/yarn'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      ls -l
      cd backend
      ls -l
      yarn install
      yarn jest
