steps:
- id: 'ls'
  name: "bash"
  args:
    - "-c"
    - |
      echo "hello"
      pwd
      ls -la
- id: 'backend yarn install'
  name: 'gcr.io/cloud-builders/yarn'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      cd backend
      yarn install
- id: 'backend yarn start'
  name: 'gcr.io/cloud-builders/yarn'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      ls -la
      cd backend
      yarn start &
- id: 'backend check alive'
  name: 'gcr.io/cloud-builders/yarn'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      sleep 5
      curl http://localhost:3000



