steps:
- id: 'cypress install'
  name: 'gcr.io/cloud-builders/yarn'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      yarn install
- id: 'cypress image pull'
  name: cypress/included:10.9.0
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      echo "cypress ready"
- id: 'cypress run'
  name: cypress/included:10.9.0
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      yarn cypress run

      #- id: 'backend yarn install'
      #  name: 'gcr.io/cloud-builders/yarn'
      #  entrypoint: 'sh'
      #  args:
      #    - "-c"
      #    - |
      #      cd backend
      #      yarn install
      #- id: 'backend yarn start'
      #  name: 'gcr.io/cloud-builders/yarn'
      #  entrypoint: 'sh'
      #  args:
      #    - "-c"
      #    - |
      #      ls -la
      #      cd backend
      #      sh ci.sh

