steps:
- id: 'ls'
  name: "bash"
  args:
    - "-c"
    - |
      echo "hello"
      pwd
      ls -la
- id: 'cypress install'
  name: 'gcr.io/cloud-builders/yarn'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      yarn install
- id: 'cypress run'
  name: 'gcr.io/cloud-builders/yarn'
  entrypoint: 'sh'
  args:
    - "-c"
    - |
      yarn cypress run
      #- id: 'backend yarn install'
      #  name: 'gcr.io/cloud-builders/yarn'
      #  entrypoint: 'sh'
      #  args:
      #    - "-c"
      #    - |
      #      cd backend
      #      yarn install
      #- id: 'backend yarn start'
      #  name: 'gcr.io/cloud-builders/yarn'
      #  entrypoint: 'sh'
      #  args:
      #    - "-c"
      #    - |
      #      ls -la
      #      cd backend
      #      sh ci.sh

